#!/bin/sh

# The purpose of this script is to create a "development" verions
# out of the regular, installed iplots library. 
# "Development" means, that R/iplots and iplots.jar are actually
# softlinks to this package sources

SWD=`pwd`

if [ -z $R_HOME ]; then
    R_HOME=`R CMD /bin/sh -c 'echo $R_HOME'`
fi
    
if [ -z R_HOME ]; then
    echo "Sorry, cannot find R_HOME. Please make sure R is on the PATH or R_HOME is set."
    exit 1
fi

echo "R_HOME: ${R_HOME}"

IPL=${R_HOME}/library/iplots

if [ ! -e ${IPL}/CONTENTS ]; then
    echo "${IPL} doesn't exist. You'll need to run the regular R CMD INSTALL before turning that installation into a development one."
    exit 1
fi

echo "Removing previous links/contents ..."
rm -f ${IPL}/cont/iplots.jar
rm -f ${IPL}/R/iplots

echo "Using compiled jar ..."
if [ -e /Work/builds ]; then
   BUILDIR=/Work/builds
fi
if [ -e /Builds ]; then
   BUILDIR=/Builds
fi
echo "Build directory: ${BUILDIR}/Klimt.app"
if [ ! -e ${BUILDIR}/Klimt.app/Contents/Resources/Java/Klimt.jar ]; then
   echo "Sorry, but currently I don't know how to re-build Java sources."
   echo "Please compile the framework with Project Builder (Klimt.app in /Work/builds)"
   exit 1
fi

echo "Creating links ..."

cd ${IPL}/R
ln -sf ${SWD}/R/iplots.R iplots

cd ${IPL}/cont
ln -sf ${BUILDIR}/Klimt.app/Contents/Resources/Java/Klimt.jar iplots.jar

echo "Done."
