#!/bin/sh

: ${JFLAGS=-target 1.4 -source 1.4}

SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/iplots
echo "Copying package base ..."
cp -r ../iplots /tmp

rm -rf /tmp/iplots.java
mkdir /tmp/iplots.java

JARFILE=$1

if [ -z $JARFILE ]; then
    JARFILE="../../../org/iplots.jar";
    rm -f $JARFILE
    make -C ../../../org iplots.jar
fi
if [ ! -e $JARFILE ]; then
    echo "*** ERROR: cannot find iplots.jar in $JARFILE" >&2
    echo "Please check out org/rosuda or set JARFILE correspondingly" >&2
    exit 2
fi

#echo "Copying sources ..."
#if [ ! -e ../../../org/rosuda/iplots/Framework.java ]; then
#   echo "Can't find sources! Check out both R and org/rosuda modules!"
#   exit 1
#fi
#find ../../../org/rosuda name \*.java -exec cp \{\} /tmp/iplots.java/ \;

#cp ../../../java/stat/klimt/src/*.java /tmp/iplots.java

cp ../../../org/rosuda/iplots/iPlots.jpg /tmp/iplots.java/iPlots.jpg
cp ../../../org/rosuda/ibase/Common.java /tmp/iplots.java/Common.java

# we need an absolute path because we're running in /tmp
JBASE=`dirname $JARFILE`
JNAME=`basename $JARFILE`
cd $JBASE
JARFILE=`pwd`/$JNAME

cd /tmp/iplots.java
jar fx ${JARFILE}
mv iPlots.jpg splash.jpg

rm /tmp/iplots/mkdist

cd /tmp/iplots
VER=`awk -v ORS= '/Package version:/ { print $4 }' R/iplots.R`
echo "iplots version ${VER}"

cd /tmp/iplots.java
#echo Removing plugins and wrappers ...
#rm -f PluginDeriveVar.java PluginGetTreeR.java PluginStartRserve.java PoGraSSSVG.java tfw.java Wrapper.java StaticReader.java PGSviewer.java

if [ `uname` != "Darwin" ]; then
    echo "Non-Mac platform. MacOS (MRJ) support will NOT be compiled."
    rm -f org/rosuda/klimt/PlatformMac.java
    rm -f org/rosuda/util/PlatformMac.java
fi

# adjust version number
echo "Adjust version number and re-compile Common.java ..."
cat Common.java | sed "s/Version=\"[0-9]*.[0-9]*\"/Version=\"${VER}\"/" > c
rm Common.java
mv c org/rosuda/ibase/Common.java
echo "javac $JFLAGS org/rosuda/ibase/Common.java"
javac $JFLAGS org/rosuda/ibase/Common.java
#echo Compiling sources ...
#javac -O *.java
echo Creating archive ...
jar fc iplots.jar org splash.jpg

echo "Copying java archive ..."
mkdir -p /tmp/iplots/inst/cont
cp iplots.jar /tmp/iplots/inst/cont

cd /tmp/iplots
echo "Removing CVS stuff ..."
rm -rf `find . -name CVS -or -name \*~ -or -name .#\*`
#echo "Updating INDEX ..."
cd ..
#R CMD Rdindex iplots > iplots/INDEX
echo "Updating version ..."
cd iplots
cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
mv d DESCRIPTION
echo "Creating package ..."
cd ..
tar fcz iplots_${VER}.tar.gz iplots
cd ${SWD}
cp /tmp/iplots_${VER}.tar.gz ..
rm -rf /tmp/iplots /tmp/iplots.java
echo "Done."
ls -l ../iplots_${VER}.tar.gz
