#!/bin/sh

: ${JFLAGS=-target 1.4 -source 1.4}

PNAME=iplots
SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -r . /tmp/${PNAME}

if [ ! -e "/tmp/${PNAME}/java/org/Makefile" ]; then
    echo "*** ERROR: cannot find Java sources"
    exit 1
fi

cd /tmp/${PNAME}
VER=`sed -n -e 's/.*Package version: \([0-9.-]\{1,\}\).*/\1/p' R/iplots.R`
echo "iplots version ${VER}"

# adjust version number
echo "Adjust version number ..."
cat java/org/rosuda/ibase/Common.java | sed "s/Version=\"[0-9]*.[0-9]*\"/Version=\"${VER}\"/" > java/org/rosuda/ibase/Common.java.tmp && mv java/org/rosuda/ibase/Common.java.tmp java/org/rosuda/ibase/Common.java

echo "Compile Java sources ..."
make -C java/org iplots.jar
JARFILE="java/org/iplots.jar"
if [ ! -e "${JARFILE}" ]; then
    echo "*** ERROR: unable to compile Java sources"
    exit 1
fi

echo "Copying java archive ..."
mkdir -p inst/java
cp "${JARFILE}" inst/java

rm -rf mkdist java 

echo "Removing CVS/SVN and backup stuff ..."
rm -rf `find . -name CVS -or -name .svn -or -name \*~ -or -name .#\*`

#echo "Updating INDEX ..."
#cd ..
#R CMD Rdindex iplots > iplots/INDEX
#cd iplots

echo "Updating version ..."
cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d && mv d DESCRIPTION
rm -f `find . -name ._\*`

echo "Creating package ..."
cd ..
R CMD build ${PNAME}
cd ${SWD}
cp /tmp/${PNAME}_${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz
